### PR TITLE
Add support for window.addEventListener

### PR DESCRIPTION
**Pull request by arv**
https://github.com/toolkitchen/ShadowDOM/issues/43

### CODE REVIEW

**Comment by sjmiles** [comment]
Not working correctly on FF Windows stable (19.0.2), but behavior is strange. Trying to figure it out.

**Comment by sjmiles** [comment]
On FF Windows Release (19.0.2), neither of these work:

```
Object.defineProperty(Document.prototype, 'squid', {value: Document.prototype.dispatchEvent});
console.warn(Document.prototype.squid ? "OK" : "FAIL");
>> FAIL

Document.prototype.squid = Document.prototype.dispatchEvent;
console.warn(Document.prototype.squid ? "OK" : "FAIL");
>> FAIL
```

**Comment by arv** [comment]
It seems 20.0 is the current stable version of Firefox and that does not show the same issue.

**Comment by sjmiles** [comment]
Confirmed, it's been fixed in last week.

**Pull request merged**
