### PR TITLE
Bring shadow dom algorithms up to date

### PR DESCRIPTION
**Pull request by arv**
This is a complete update of the distribution, composition and event
path algorithms from the spec draft.

Fixes #420

### CODE REVIEW

**Comment by arv** [comment]
@sjmiles @sorvell 

I know this is big but what is your time frame for reviewing this?

**Comment by dfreedm** [comment]
I'll take a look

**Comment by dfreedm** [comment]
Looks like something in here is crashing IE 11 tabs.

**Comment by arv** [comment]
You know what. I saw that too. But then I checked out a really old version and it still crashed. So, after resetting IE's cache it no longer crashed on head. Maybe I need to spend some more time on figuring out why it crashed.

**Comment by arv** [comment]
And now I cannot get IE11 to crash any more.

**Comment by arv** [comment]
PTAL

**Comment by dfreedm** [comment]
LGTM

**Pull request merged**
