### PR TITLE
Wrap MutationObserver and MutationRecord

### PR DESCRIPTION
**Pull request by arv**
Fixes #54

### CODE REVIEW

**Comment by arv** [comment]
This should allow you to retire https://github.com/toolkitchen/PointerEvents/tree/shadow-dom-polyfill

**Comment by dfreedm** [comment]
I'm going to test with my use in PointerEvents:

```
observe(document | shadow root,
  {attributes: true, attributeFilter: [...], childList: true, subtree: true}
)
```

**Comment by arv** [comment]
That reminds me. I should probably special case `document` since we might get an unwrapped document. I can do that in this PR or in a new one. Either way is fine by me.

**Comment by dfreedm** [comment]
I was just going to mention that actually :+1: 
Would it be ok to do it in this one? It's the only case I had left to wrap.

Also, maybe just one or two tests with observer watching attributes change.

**Comment by arv** [comment]
There is a test watching attribute changes already. It is not as interesting because it does not need any special code.

**Comment by arv** [comment]
PTAL

**Comment by dfreedm** [comment]
Ah my eyes missed that test :(

LGTM!

**Pull request merged**
