### PR TITLE
adoptNode needs to adopt the shadow root too

### PR DESCRIPTION
**Pull request by arv**

### CODE REVIEW

**Comment by sorvell** [comment]
LGTM

**Comment by arv** [comment]
This is not sufficient. I need to also adopt older shadow roots

**Comment by dfreedm** [comment]
For older roots, you can just iterate with `nextOlderShadowTreeTable` right?

**Comment by arv** [comment]
Yup.

On Fri, Jun 14, 2013 at 4:53 PM, Daniel Freedman
notifications@github.comwrote:

> For older roots, you can just iterate with nextOlderShadowTreeTable right?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Polymer/ShadowDOM/pull/167#issuecomment-19481099
> .

## 

erik

**Pull request merged**
