### PR TITLE
fix: select the <q> node

### PR DESCRIPTION
**Pull request by vicb**

### CODE REVIEW

**Comment by arv** [comment]
Which document is this? This is just an arbitrary example. Changing to q does not make the point better or worse.

**Comment by vicb** [comment]
@arv I think the doc is wrong as is. If you mind to read 5 lines below this change, you'll see what I mean.

**Comment by arv** [comment]
I see. Yeah, then `q` makes more sense.

**Comment by vicb** [comment]
So any plan to re-open / merge this PR ?

**Comment by arv** [comment]
I just edited the file using githubs online editor. Quicker than waiting
for CLA signing and all the other process... Sorry.

If you want to get the credit for this I can revert the change, wait for
the CLA and do this again.

On Sat, Aug 2, 2014 at 2:09 PM, Victor Berchet notifications@github.com
wrote:

> So any plan to re-open / merge this PR ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Polymer/ShadowDOM/pull/483#issuecomment-50970109.

## 

erik

**Comment by vicb** [comment]
No I don't request credit for having fixed 2 chars :)
I just wanted to make sure it had been fixed.
Thanks,
Vic

**Pull request closed without merging**
