### PR TITLE
Fix issue with Element not having all the required properties

### PR DESCRIPTION
**Pull request by arv**
Fixes #349

### CODE REVIEW

**Comment by arv** [comment]
@rafaelw The IE issue should not affect your svg:template patch since the namespaceURI stays correct even though the interface is not correct.

**Comment by arv** [comment]
Ping

**Comment by dfreedm** [comment]
LGTM!

**Comment by dfreedm** [comment]
Ah nuts, getting some failed tests on Safari with this patch.

**Pull request merged**
