### PR TITLE
Explicitly read/write ShadowDOMPolyfill on window

### PR DESCRIPTION
**Pull request by timoxley**
Would be good to adopt a policy of always explicitly attaching/reading from global scope to make it nice and clear where the data is coming from… and to ensure the code executes correctly when `this` or the global scope might have been altered.

### CODE REVIEW

**Comment by arv** [comment]
LGTM

Did you sign the CLA?
https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md

**Comment by timoxley** [comment]
@arv I have signed the CLA

**Comment by arv** [comment]
LGTM

I'll manually merge this

**Comment by timoxley** [comment]
:+1: thank you

**Pull request merged**
